// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCR2X7I5-grAE1stcnyvtbwSTsfHazBHQ8',
    appId: '1:982979576853:web:4bb5e9d45f5ee366db7a1c',
    messagingSenderId: '982979576853',
    projectId: 'yublagov-mynotes',
    authDomain: 'yublagov-mynotes.firebaseapp.com',
    storageBucket: 'yublagov-mynotes.appspot.com',
    measurementId: 'G-K24XY1N55N',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA6-uQcY-4stzlVbvNiNLPar-_f1w-4rVU',
    appId: '1:982979576853:android:cf9b2ccb73947bc1db7a1c',
    messagingSenderId: '982979576853',
    projectId: 'yublagov-mynotes',
    storageBucket: 'yublagov-mynotes.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDTW4iCfN8x12nVMudn8GJzLEP03qCXlbg',
    appId: '1:982979576853:ios:7191b7008d75deeddb7a1c',
    messagingSenderId: '982979576853',
    projectId: 'yublagov-mynotes',
    storageBucket: 'yublagov-mynotes.appspot.com',
    iosClientId: '982979576853-0oea2vu4q1ab3mol4fdmr13pnoafh1ji.apps.googleusercontent.com',
    iosBundleId: 'com.example.learningDurt',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDTW4iCfN8x12nVMudn8GJzLEP03qCXlbg',
    appId: '1:982979576853:ios:7191b7008d75deeddb7a1c',
    messagingSenderId: '982979576853',
    projectId: 'yublagov-mynotes',
    storageBucket: 'yublagov-mynotes.appspot.com',
    iosClientId: '982979576853-0oea2vu4q1ab3mol4fdmr13pnoafh1ji.apps.googleusercontent.com',
    iosBundleId: 'com.example.learningDurt',
  );
}
